version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: anticair_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=anticair
      - MYSQL_USER=anticair
      - MYSQL_PASSWORD=anticair123
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb_data:
    name: anticair_db_data